version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:
      - checkout
      
      - restore_cache:
          key: helloworld-cicd-{{ checksum "pom.xml" }}
      
      - run:
          name: Build Step
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests

      - run:
          name: Test Step
          command: |
            echo 'Testando...'
            mvn test
            
      - save_cache:
          paths:
            - ~/.m2
          key: helloworld-cicd-{{ checksum "pom.xml" }}
          
      - setup_remote_docker
      
      - run:
          name: Install Docker
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/bin
            
      - run:
          name: Install Heroku CLI
          command: |
            curl -L -o /tmp/heroku-install.sh https://cli-assets.heroku.com/install.sh
            sh /tmp/heroku-install.sh
            heroku --version
       
      - run:
          name: Deploy to Heroku APP
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
          