version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:
      - checkout
      
      - restore_cache:
          key: helloworld-cicd-{{ checksum "pom.xml" }}
      
      - run:
          name: Build Step
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests
      
      - save_cache:
          paths:
            - ~/.m2
          key: helloworld-cicd-{{ checksum "pom.xml" }}
          
      - setup_remote_docker
      
      - run:
          name: Install Docker
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/bin
            
      - run: 
          name: Docker Build
          command: | 
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t rcvieira/helloworld-cicd:$TAG