version: 2.1
jobs:
  build-phase:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:
      - checkout
      
      - restore_cache:
          key: helloworld-cicd-{{ checksum "pom.xml" }}
      
      - run:
          name: Build Step
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests

      - run:
          name: Test Step
          command: |
            echo 'Testando...'
            mvn test
 
      - save_cache:
          paths:
            - ~/.m2
          key: helloworld-cicd-{{ checksum "pom.xml" }}
          
      - setup_remote_docker

      - run:
          name: Prepare Push Docker Image - Install Docker & Heroku
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/bin
            curl -L -o /tmp/heroku-install.sh https://cli-assets.heroku.com/install.sh
            sh /tmp/heroku-install.sh
            heroku --version
      
      - run:
          name: Push Docker Image do Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $HEROKU_APP_NAME

  quality-phase:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=rcvieira_helloworld-cicd -Dsonar.organization=rcvieira -Dsonar.host.url=https://sonarcloud.io

  deploy-phase:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:               
      - run:
          name: Prepare Deploy do Heroku - Install Docker & Heroku
          command: |
            set -x
            VER="18.09.3"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv -f /tmp/docker/* /usr/bin
            curl -L -o /tmp/heroku-install.sh https://cli-assets.heroku.com/install.sh
            sh /tmp/heroku-install.sh
            heroku --version
      
      - run:
          name: Deploy to Heroku APP
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  version: 2
  workflow-principal:
    jobs:
      - build-phase
      - quality-phase:
          context: SonarCloud
          requires:
            - build-phase      
      - deploy-phase:
          requires:
            - quality-phase