version: 2.1
jobs:
  build:
    docker:
      - image: circleci/circleci/openjdk:8-jdk-strech      
    steps:
      - checkout      
      - run:
        name: Compila
        command: mvn clean package -DskipTests