version: 2.1
jobs:
  build-stage:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    environment:
      PORT: 8080    
    steps:
      - checkout
      
      - restore_cache:
          key: helloworld-cicd-{{ checksum "pom.xml" }}
      
      - run:
          name: Build
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests

      - run:
          name: Test
          command: |
            echo 'Testando...'
            mvn test

      - run: 
          name: Quality - Analyze on SonarCloud
          command: mvn verify -DskipTests=true sonar:sonar -Dsonar.projectKey=rcvieira_helloworld-cicd -Dsonar.organization=rcvieira -Dsonar.host.url=https://sonarcloud.io

      - store_test_results:
          path: target/surefire-reports

      - save_cache:
          paths:
            - ~/.m2
          key: helloworld-cicd-{{ checksum "pom.xml" }}

      - setup_remote_docker

      - run:
          name: Acceptance Tests - Run App & Tests
          command: |
            ls -la /home/circleci/project
            docker build -t helloworld-cicd:latest .
            docker run --name helloworld-cicd --rm -d -e PORT -p 8080:$PORT/tcp helloworld-cicd:latest
            # docker run --network container:helloworld-cicd --name ITTests -v ~/.m2:/root/.m2 -v /home/circleci/project:/usr/srv/mymaven -w /usr/srv/mymaven maven mvn verify -DskipUTs=true 
            docker run --network container:helloworld-cicd --name ITTests -v ~/.m2:/root/.m2 -v /home/circleci/project:/usr/srv/mymaven -w /usr/srv/mymaven maven ls -la /usr/srv/mymaven

      - store_test_results:
          path: target/failsafe-reports

      - setup_remote_docker

      - run:
          name: Deploy - Install Heroku CLI
          command: |
            set -x
            curl -L -o /tmp/heroku-install.sh https://cli-assets.heroku.com/install.sh
            sh /tmp/heroku-install.sh
            heroku --version
      
      - run:
          name: Deploy - Install to Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  version: 2
  workflow-principal:
    jobs:
      - build-stage:
          context: SonarCloud