version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:
      - checkout
      
      - restore_cache:
          key: helloworld-cicd-{{ checksum "pom.xml" }}
      
      - run:
          name: Build Step
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests
      
      - save_cache:
          paths:
            - ~/.m2
          key: helloworld-cicd-{{ checksum "pom.xml" }}
          
      - store_artifacts:
          path: target/helloworld-cicd*.war