version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch      
    steps:
      - checkout
      - run:
          name: Build Step
          command: |
            echo 'Compilando...'
            mvn clean package -DskipTests